### ISSUE TITLE
Error: object 'PrediObj' not found

### ISSUE THREAD

**Issue by christophM** [compstat-lmu/iml-shiny-summary#4]
When I upload a model (iml Predictor object), I get the following error: 

`object 'PrediObj' not found`

I got the model with following code:

```
library(iml)
library(mlr)

lrn = makeLearner("regr.ranger")
mod = train(lrn, bh.task)
dat = getTaskData(bh.task)
pred = Predictor$new(mod, data = dat, y = "medv")
saveRDS(pred, file = "test.RDS")a

```

**Comment by QWERTZ11** [comment]
Yes, I got it also.

I have separated the codes for "upload" from others and save as "shiny.R"
and it works.

**Comment by christophM** [comment]
Can you make it work for app.R?

**Comment by QWERTZ11** [comment]
Yes, I try.

**Comment by QWERTZ11** [comment]
done.
