### ISSUE TITLE
Add tab for Local Interpretation (Shapley Values)

### ISSUE THREAD

**Issue by christophM** [compstat-lmu/iml-shiny-summary#6]
For the local interpretation page, show the table with the data on top of the page.
From this table, the user can pick an observation.
For this observation the Shapley Values are computed and the graphic shown below the table.

For selection of row: https://rstudio.github.io/DT/shiny.html
add row numbers as well

**Comment by QWERTZ11** [comment]
done

**Comment by christophM** [comment]
Thank you!

**Comment by QWERTZ11** [comment]
:)
